### ISSUE TITLE
 Draw Shapes doesn't work in Demo(Version 2.2.2)

### ISSUE THREAD

**Issue by shujuliuguyu** [lolochristen/OpenLayers.Blazor#83]
1. Visit https://openlayers-blazor-demo.laurent-christen.ch/drawdemo  or  https://openlayers-blazor-demo.laurent-christen.ch/drawdemo/osm
2. Open Developer tools, switch to Console
3. Click Draw ,try to draw point,linestring,polygon,cricle
4. Console display:
openlayers_interop.min.js?v=0.0.0.0:1  Uncaught TypeError: i.getShapeStyleAsync is not a function
    at O.interaction.Draw.<anonymous> (openlayers_interop.min.js?v=0.0.0.0:1:14800)
    at O.interaction.Draw.dispatchEvent (ol.min.js:1:2477)
    at O.interaction.Draw.finishDrawing (ol.min.js:444:199557)
    at O.interaction.Draw.handleUpEvent (ol.min.js:444:194391)
    at O.interaction.Draw.handleEvent (ol.min.js:1:162924)
    at O.interaction.Draw.handleEvent (ol.min.js:444:190101)
    at Bh.handleMapBrowserEvent (ol.min.js:1:184699)
    at jl.dispatchEvent (ol.min.js:1:2477)
    at jl.handlePointerUp_ (ol.min.js:1:149109)
